const defaultProducts=[
{id:1,name:'Spotify Premium 1 Bulan',category:'Langganan',price:15000,emoji:'🎵',description:'Akses premium 1 bulan.',active:true},
{id:2,name:'Canva Pro 1 Bulan',category:'Tools',price:12000,emoji:'🎨',description:'Template dan fitur Pro.',active:true},
{id:3,name:'Disney+ 1 Bulan',category:'Streaming',price:18000,emoji:'🎬',description:'Paket streaming digital.',active:true},
{id:4,name:'ChatGPT Plus',category:'AI',price:25000,emoji:'🤖',description:'Paket AI premium.',active:true},
{id:5,name:'YouTube Premium',category:'Streaming',price:17000,emoji:'▶️',description:'Streaming tanpa iklan.',active:true},
{id:6,name:'CapCut Pro',category:'Tools',price:13000,emoji:'✂️',description:'Fitur editing premium.',active:true},
{id:7,name:'Game Voucher',category:'Game',price:20000,emoji:'🎮',description:'Voucher digital demo.',active:true},
{id:8,name:'Notion Plus',category:'Tools',price:14000,emoji:'📝',description:'Fitur produktivitas premium.',active:true}
];
const getProducts=()=>{let p=JSON.parse(localStorage.getItem('lm_products'));if(!p){localStorage.setItem('lm_products',JSON.stringify(defaultProducts));return defaultProducts}return p};
let products=getProducts(), cart=JSON.parse(localStorage.getItem('lm_cart')||'[]'), selected='Semua';
const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
function render(){products=getProducts();let active=products.filter(p=>p.active);document.querySelector('#statProducts').textContent=active.length;document.querySelector('#productCount').textContent=`${active.length} produk ready`;let cats=['Semua',...new Set(active.map(p=>p.category))];document.querySelector('#categoryChips').innerHTML=cats.map(c=>`<button class="chip ${selected===c?'active':''}" data-cat="${c}">${c==='Semua'?'✦':'🌸'} ${c}</button>`).join('');let q=document.querySelector('#searchInput').value.toLowerCase();let list=active.filter(p=>(selected==='Semua'||p.category===selected)&&(p.name+p.category+p.description).toLowerCase().includes(q));document.querySelector('#productGrid').innerHTML=list.length?list.map(p=>`<article class="product"><div class="product-img">${p.emoji||'🌸'}</div><div class="product-body"><span class="tag">${p.category}</span><h3>${p.name}</h3><p class="muted">${p.description||''}</p><div class="price">${rupiah(p.price)}</div><button class="buy" data-buy="${p.id}">Beli Sekarang</button></div></article>`).join(''):`<div class="empty">Produk tidak ditemukan.</div>`;document.querySelector('#cartCount').textContent=cart.reduce((s,i)=>s+i.qty,0)}
function saveCart(){localStorage.setItem('lm_cart',JSON.stringify(cart));render()}
function openCart(){document.querySelector('#cartModal').classList.add('show');let box=document.querySelector('#cartItems');if(!cart.length){box.innerHTML='<p class="muted">Keranjang masih kosong.</p>';document.querySelector('#checkoutBtn').disabled=true;return}document.querySelector('#checkoutBtn').disabled=false;box.innerHTML=cart.map(i=>{let p=products.find(x=>x.id===i.id);return `<div class="cart-row"><div><b>${p?.name||'Produk'}</b><br><small>${i.qty} × ${rupiah(p?.price||0)}</small></div><button class="action" data-remove="${i.id}">Hapus</button></div>`}).join('');document.querySelector('#cartTotal').textContent=rupiah(cart.reduce((s,i)=>{let p=products.find(x=>x.id===i.id);return s+(p?.price||0)*i.qty},0))}
document.addEventListener('click',e=>{let cat=e.target.closest('[data-cat]');if(cat){selected=cat.dataset.cat;render()}let buy=e.target.closest('[data-buy]');if(buy){let id=+buy.dataset.buy, item=cart.find(x=>x.id===id);item?item.qty++:cart.push({id,qty:1});saveCart();openCart()}let rem=e.target.closest('[data-remove]');if(rem){cart=cart.filter(x=>x.id!==+rem.dataset.remove);saveCart();openCart()}});
document.querySelector('#searchInput').addEventListener('input',render);document.querySelector('#cartBtn').onclick=openCart;document.querySelector('#closeCart').onclick=()=>document.querySelector('#cartModal').classList.remove('show');document.querySelector('#closeCheckout').onclick=()=>document.querySelector('#checkoutModal').classList.remove('show');document.querySelector('#checkoutBtn').onclick=()=>{document.querySelector('#cartModal').classList.remove('show');document.querySelector('#checkoutModal').classList.add('show')};
document.querySelector('#checkoutForm').addEventListener('submit',e=>{e.preventDefault();let fd=new FormData(e.target), total=cart.reduce((s,i)=>{let p=products.find(x=>x.id===i.id);return s+(p?.price||0)*i.qty},0), order={id:'LM'+Date.now().toString().slice(-7),name:fd.get('name'),email:fd.get('email'),phone:fd.get('phone'),payment:fd.get('payment'),items:cart,total,status:'Menunggu Pembayaran',created:new Date().toISOString()};let orders=JSON.parse(localStorage.getItem('lm_orders')||'[]');orders.unshift(order);localStorage.setItem('lm_orders',JSON.stringify(orders));cart=[];saveCart();document.querySelector('#orderResult').innerHTML=`<div class="panel"><b>Pesanan berhasil dibuat!</b><p>ID Pesanan: <b>${order.id}</b></p><p>Total: <b>${rupiah(total)}</b></p><p class="muted">Demo: status pembayaran belum terhubung ke gateway.</p></div>`;e.target.reset()});render();
